### ISSUE TITLE
Internal Error from api/archive,  please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by xasima** [superdesk/superdesk#1806]
I had tried to start superdesk via docker/docker-local-demo.sh on  specific host by changing both  'superdesk' and 'pubapi'  parts in 'docker/common.yml' 

```
   - AMAZON_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXXXX
   - AMAZON_CONTAINER_NAME=superdeckcontainer
   - AMAZON_REGION=us-west-2
   - AMAZON_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXX/a

   - SUPERDESK_URL=http://superdesk.***.com/api
   #- SUPERDESK_WS_URL is omitted pubapi
   - SUPERDESK_WS_URL=ws://superdesk.***.com/ws
   - PUBLICAPI_URL=http://superdesk.***.com/pubapi
   - SUPERDESK_CLIENT_URL=http://superdesk.***.com
   - SUPERDESK_TESTING=True
```

I had also allowed all write / read operations on AWS S3 bucket for this user.  

If I click  Content -> Create new item -> Plain text, I have got  500 (INTERNAL SERVER ERROR)  from 'api/archive', and  the following is appeared in  a running console

```
superdesk_1 | 07:59:43 work.1    | An error occurred (InvalidRequest) when calling the PutObject operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. level=ERROR process=Worker-6
superdesk_1 | 07:59:43 work.1    | Traceback (most recent call last):
superdesk_1 | 07:59:43 work.1    |   File "/usr/local/lib/python3.4/dist-packages/superdesk/io/commands/update_ingest.py", line 467, in ingest_item
superdesk_1 | 07:59:43 work.1    |     update_renditions(item, href, old_item)
superdesk_1 | 07:59:43 work.1    |   File "/usr/local/lib/python3.4/dist-packages/superdesk/io/commands/update_ingest.py", line 525, in update_renditions
superdesk_1 | 07:59:43 work.1    |     file_guid = app.media.put(content, filename, content_type, metadata)
superdesk_1 | 07:59:43 work.1    |   File "/usr/local/lib/python3.4/dist-packages/superdesk/storage/amazon/amazon_media_storage.py", line 165, in put
superdesk_1 | 07:59:43 work.1    |     ContentType=content_type, Metadata=file_metadata, **self.kwargs)
superdesk_1 | 07:59:43 work.1    |   File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 231, in _api_call
superdesk_1 | 07:59:43 work.1    |     return self._make_api_call(operation_name, kwargs)
superdesk_1 | 07:59:43 work.1    |   File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 489, in _make_api_call
superdesk_1 | 07:59:43 work.1    |     raise ClientError(parsed_response, operation_name)
superdesk_1 | 07:59:43 work.1    | botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the PutObject operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
```

How to fix that? Can we enforce to use  signatureVersion: 'v4' when access AWS us-west S3 region?

**Comment by petrjasek** [comment]
seems like an issue with [boto3](/boto/boto3) library.
can you pls check some example from [quickstart](http://boto3.readthedocs.org/en/latest/guide/quickstart.html#quickstart) to see if you get the same error?

**Comment by naspeh** [comment]
We already have support for
> signatureVersion: 'v4'

So this issue can be closed.

Ref: https://github.com/superdesk/superdesk-core/blob/c23d3adb63f4f05a93ed5edbff4b1fe3b6d26eb5/superdesk/storage/amazon_media_storage.py#L71
