### ISSUE TITLE
ElasticsearchIllegalArgumentException: Alias [superdesk] has more than one indices associated with it

### ISSUE THREAD

**Issue by xasima** [superdesk/superdesk#1807]
When starting `./script/docker-local-demo.sh` with a dedicated hostname (see #1806 for details for configuration details), the following elastic search error is being appeared in a running console. 

```
Task superdesk.io.commands.update_ingest.update_provider[6d1ca194-2b43-4ffb-abdb-479d355233a8] raised unexpected: RequestError(400, "
ElasticsearchIllegalArgumentException[Alias [superdesk] has more than one indices associated with it [[superdesk_d1612723, superdesk_02bd8ddf, superdesk_acdabaad, super
desk_42af53df, superdesk_8dcb875f, superdesk_f170b5f3, superdesk_c809d8f3, superdesk_2cf93a59, superdesk_5b0344b7]], can't execute a single index op]", {'status': 400, 
'error': "ElasticsearchIllegalArgumentException[Alias [superdesk] has more than one indices associated with it [[superdesk_d1612723, superdesk_02bd8ddf, superdesk_acdab
aad, superdesk_42af53df, superdesk_8dcb875f, superdesk_f170b5f3, superdesk_c809d8f3, superdesk_2cf93a59, superdesk_5b0344b7]], can't execute a single index op]"}) level
=ERROR process=MainProcess 
superdesk_1 | 11:08:16 work.1    | Traceback (most recent call last):
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 240, in trace_task
superdesk_1 | 11:08:16 work.1    |     R = retval = fun(*args, **kwargs)
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/superdesk/celery_app.py", line 113, in __call__
superdesk_1 | 11:08:16 work.1    |     return super().__call__(*args, **kwargs)
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 438, in __protected_call__
superdesk_1 | 11:08:16 work.1    |     return self.run(*args, **kwargs)
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/superdesk/io/commands/update_ingest.py", line 230, in update_provider
superdesk_1 | 11:08:16 work.1    |     ingest_items(items, provider, feeding_service, rule_set, routing_scheme)
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/superdesk/io/commands/update_ingest.py", line 422, in ingest_items
superdesk_1 | 11:08:16 work.1    |     app.data._search_backend('ingest').bulk_insert('ingest', [item for item in all_items
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/eve_elastic/elastic.py", line 409, in bulk_insert
superdesk_1 | 11:08:16 work.1    |     res = bulk(self.es, docs, stats_only=False, **kwargs)
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/elasticsearch/helpers/__init__.py", line 188, in bulk
superdesk_1 | 11:08:16 work.1    |     for ok, item in streaming_bulk(client, actions, **kwargs):
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/elasticsearch/helpers/__init__.py", line 160, in streaming_bulk
superdesk_1 | 11:08:16 work.1    |     for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/elasticsearch/helpers/__init__.py", line 89, in _process_bulk_chunk
superdesk_1 | 11:08:16 work.1    |     raise e
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/elasticsearch/helpers/__init__.py", line 85, in _process_bulk_chunk
superdesk_1 | 11:08:16 work.1    |     resp = client.bulk('\n'.join(bulk_actions) + '\n', **kwargs)
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
superdesk_1 | 11:08:16 work.1    |     return func(*args, params=params, **kwargs)
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/elasticsearch/client/__init__.py", line 782, in bulk
superdesk_1 | 11:08:16 work.1    |     doc_type, '_bulk'), params=params, body=self._bulk_body(body))
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/elasticsearch/transport.py", line 307, in perform_request
superdesk_1 | 11:08:16 work.1    |     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
superdesk_1 | 11:08:16 work.1    |     self._raise_error(response.status, raw_data)
superdesk_1 | 11:08:16 work.1    |   File "/usr/local/lib/python3.4/dist-packages/elasticsearch/connection/base.py", line 105, in _raise_error
superdesk_1 | 11:08:16 work.1    |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
superdesk_1 | 11:08:16 work.1    | elasticsearch.exceptions.RequestError: TransportError(400, "ElasticsearchIllegalArgumentException[Alias [superdesk] has more than one indices associated with it [[superdesk_d1612723, superdesk_02bd8ddf, superdesk_acdabaad, superdesk_42af53df, superdesk_8dcb875f, superdesk_f170b5f3, superdesk_c809d8f3, superdesk_2cf93a59, superdesk_5b0344b7]], can't execute a single index op]")
```

**Comment by petrjasek** [comment]
thx for reporting, @actionless can you check this pls?

**Comment by actionless** [comment]
i had no chance to reproduce the problem, but it seems like that happens  when different superdesk instances are starting with the same settings (ie including elasticsearch db name)

you can delete redundant indexes or just remove `./data/elastic/` directory and restart elasticsearch container to completely flush it
