### ISSUE TITLE
The instructions don't work on a Mac with Docker Machine

### ISSUE THREAD

**Issue by will-in-wi** [superdesk/superdesk#2049]
This might be intentional, but I thought I'd report.

It looks like it is a known issue in the ES docker project: https://github.com/docker-library/elasticsearch/issues/27

The output I get is (trimmed slightly for length):

```elastic_1   | [2016-05-23 16:56:09,335][INFO ][node                     ] [Agamotto] version[1.5.2], pid[1], build[62ff986/2015-04-27T09:21:06Z]
elastic_1   | [2016-05-23 16:56:09,386][INFO ][node                     ] [Agamotto] initializing ...
elastic_1   | [2016-05-23 16:56:09,406][INFO ][plugins                  ] [Agamotto] loaded [], sites []
elastic_1   | {1.5.2}: Initialization Failed ...
elastic_1   | - ElasticsearchIllegalStateException[Failed to created node environment]
elastic_1   |   AccessDeniedException[/usr/share/elasticsearch/data/elasticsearch]
sddemo_elastic_1 exited with code 3
pubapi_1    | waiting for elastic...
pubapi_1    | waiting for mongo...
superdesk_1 | waiting for elastic on elastic:9200 ...
superdesk_1 | waiting for mongo on mongodb:27017 ...
pubapi_1    | waiting for elastic...
pubapi_1    | waiting for mongo...
superdesk_1 | waiting for elastic on elastic:9200 ...
superdesk_1 | waiting for mongo on mongodb:27017 ...
pubapi_1    | waiting for elastic...
pubapi_1    | waiting for mongo...
superdesk_1 | waiting for elastic on elastic:9200 ...
superdesk_1 | waiting for mongo on mongodb:27017 ...

```

It repeats forever at that point.
```

**Comment by quanganh206** [comment]
Hi, same problem here even I tested elastic, and mongodb work fine.

**Comment by otso** [comment]
Same here when following installation https://github.com/superdesk/superdesk/blob/master/README.md on a mac - any suggestions? @petrjasek @actionless

**Comment by petrjasek** [comment]
hi - can you pls check [manual install](https://github.com/gbbr/superdesk/blob/954711370a048bd8aa0448fd1897a1e73d2fa44c/README.md#macos) ?

**Comment by djKooks** [comment]
Hellp @petrjasek 
I am also facing an error while manual install.
```
6. For an initially empty database, you may initialize and pre-populate it by running (inside the server folder): python3 manage.py app:initialize_data && python3 manage.py app:prepopulate.
```
I got an error like below.
```
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    app = get_app()
  File "/Users/kwangin/workspace/superdesk/superdesk/server/app.py", line 53, in get_app
    app = superdesk_app(config, media_storage)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/superdesk/factory/app.py", line 129, in get_app
    app.data.init_elastic(app)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/superdesk/datalayer.py", line 44, in init_elastic
    self.elastic.init_index(app)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/eve_elastic/elastic.py", line 184, in init_index
    self.put_mapping(app, index)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/eve_elastic/elastic.py", line 270, in put_mapping
    self.es.indices.put_mapping(**kwargs)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception')
```
Is this an known issue?

**Comment by petrjasek** [comment]
thanks for reporting @djKooks , not a known issue. what elastic version are you using?

**Comment by djKooks** [comment]
@petrjasek Thanks for quick response. My elasticsearch is Version: 2.4.0

**Comment by petrjasek** [comment]
that's not yet supported, it should work fine with 1.x

**Comment by djKooks** [comment]
@petrjasek Thanks! Do you have plan to support it?

**Comment by petrjasek** [comment]
yep, but no idea yet when

**Comment by djKooks** [comment]
@petrjasek I downgraded to elasticsearch 1.7, and issue above now fixed. But there are other problem when running 'honcho start'

```
10:06:53 work.1 | Traceback (most recent call last):
10:06:53 work.1 |   File "/Users/kwangin/workspace/github_source/superdesk/venv/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
10:06:53 work.1 |     R = retval = fun(*args, **kwargs)
10:06:53 work.1 |   File "/Users/kwangin/workspace/github_source/superdesk/venv/lib/python3.5/site-packages/superdesk/celery_app.py", line 113, in __call__
10:06:53 work.1 |     return super().__call__(*args, **kwargs)
10:06:53 work.1 |   File "/Users/kwangin/workspace/github_source/superdesk/venv/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
10:06:53 work.1 |     return self.run(*args, **kwargs)
10:06:53 work.1 |   File "/Users/kwangin/workspace/github_source/superdesk/venv/lib/python3.5/site-packages/superdesk/emails/__init__.py", line 29, in send_email
10:06:53 work.1 |     return app.mail.send(msg)
10:06:53 work.1 |   File "/Users/kwangin/workspace/github_source/superdesk/venv/lib/python3.5/site-packages/flask_mail.py", line 491, in send
10:06:53 work.1 |     with self.connect() as connection:
10:06:53 work.1 |   File "/Users/kwangin/workspace/github_source/superdesk/venv/lib/python3.5/site-packages/flask_mail.py", line 144, in __enter__
10:06:53 work.1 |     self.host = self.configure_host()
10:06:53 work.1 |   File "/Users/kwangin/workspace/github_source/superdesk/venv/lib/python3.5/site-packages/flask_mail.py", line 158, in configure_host
10:06:53 work.1 |     host = smtplib.SMTP(self.mail.server, self.mail.port)
10:06:53 work.1 |   File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/smtplib.py", line 251, in __init__
10:06:53 work.1 |     (code, msg) = self.connect(host, port)
10:06:53 work.1 |   File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/smtplib.py", line 335, in connect
10:06:53 work.1 |     self.sock = self._get_socket(host, port, self.timeout)
10:06:53 work.1 |   File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/smtplib.py", line 306, in _get_socket
10:06:53 work.1 |     self.source_address)
10:06:53 work.1 |   File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/socket.py", line 711, in create_connection
10:06:53 work.1 |     raise err
10:06:53 work.1 |   File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/socket.py", line 702, in create_connection
10:06:53 work.1 |     sock.connect(sa)
10:06:53 work.1 | ConnectionRefusedError: [Errno 61] Connection refused
```
Do you know about this? 
Also, how can I know whether this is running well? Will something appear on localhost:9200?

**Comment by petrjasek** [comment]
you should see some server response on `localhost:5000/api`. on `localhost:9200` there should be elastic.
for the ui follow [client instructions](https://github.com/superdesk/superdesk#client)

**Comment by djKooks** [comment]
@petrjasek Thanks. 
While I am following [setup a dev environment with docker](DEVSETUP.md), this error shows on at last part of setup, when running `docker-compose -f docker/docker-compose-dev.yml up` after user created.

```
superdesk_1  | │ ├─┬ lodash.camelcase@3.0.1 
superdesk_1  | │ │ └─┬ lodash._createcompounder@3.0.0 
superdesk_1  | │ │   ├─┬ lodash.deburr@3.2.0 
superdesk_1  | │ │   │ └── lodash._root@3.0.1 
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 62, in main
  File "compose/cli/main.py", line 114, in perform_command
  File "compose/cli/main.py", line 848, in up
  File "compose/cli/log_printer.py", line 87, in run
  File "compose/cli/log_printer.py", line 229, in consume_queue
OverflowError: signed integer is greater than maximum
docker-compose returned -1
```
Is this known issue?

**Comment by petrjasek** [comment]
not really, seems like some issue with docker compose. can you try `build` instead of `up` ?

**Comment by djKooks** [comment]
Okay, now it working after try `build`. But there are still some issue.
I got error like below.

```
superdesk_1  |             ^
superdesk_1  | ../src/validation.cc: In static member function ‘static void Validation::Initialize(v8::Handle<v8::Object>)’:
superdesk_1  | ../src/validation.cc:112:62: error: call of overloaded ‘NODE_SET_METHOD(v8::Local<v8::FunctionTemplate>&, const char [12], void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’ is ambiguous
superdesk_1  |      NODE_SET_METHOD(t, "isValidUTF8", Validation::IsValidUTF8);
superdesk_1  |                                                               ^
superdesk_1  | ../src/validation.cc:112:62: note: candidates are:
superdesk_1  | In file included from ../src/validation.cc:8:0:
superdesk_1  | /root/.node-gyp/6.7.0/include/node/node.h:244:13: note: void node::NODE_SET_METHOD(v8::Local<v8::Template>, const char*, v8::FunctionCallback)
superdesk_1  |  inline void NODE_SET_METHOD(v8::Local<v8::Template> recv,
superdesk_1  |              ^
superdesk_1  | /root/.node-gyp/6.7.0/include/node/node.h:257:13: note: void node::NODE_SET_METHOD(v8::Local<v8::Object>, const char*, v8::FunctionCallback)
superdesk_1  |  inline void NODE_SET_METHOD(v8::Local<v8::Object> recv,
superdesk_1  |              ^
superdesk_1  | make: *** [Release/obj.target/validation/src/validation.o] Error 1
superdesk_1  | make: Leaving directory `/opt/superdesk/client-core/node_modules/utf-8-validate/build'
superdesk_1  | gyp ERR! build error 
superdesk_1  | gyp ERR! stack Error: `make` failed with exit code: 2
superdesk_1  | gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
superdesk_1  | gyp ERR! stack     at emitTwo (events.js:106:13)
superdesk_1  | gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
superdesk_1  | gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
superdesk_1  | gyp ERR! System Linux 4.4.22-moby
superdesk_1  | gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
superdesk_1  | gyp ERR! cwd /opt/superdesk/client-core/node_modules/utf-8-validate
superdesk_1  | gyp ERR! node -v v6.7.0
superdesk_1  | gyp ERR! node-gyp -v v3.3.1
superdesk_1  | gyp ERR! not ok 
superdesk_1  | npm WARN install:utf-8-validate@1.1.0 utf-8-validate@1.1.0 install: `node-gyp rebuild`
superdesk_1  | npm WARN install:utf-8-validate@1.1.0 Exit status 1
superdesk_1  | /usr/local/lib/node_modules/superdesk-core -> /opt/superdesk/client-core
superdesk_1  | /opt/superdesk/client/node_modules/superdesk-core -> /usr/local/lib/node_modules/superdesk-core -> /opt/superdesk/client-core
...
```
It looks like there are some problem on front-end core.

**Comment by petrjasek** [comment]
these are ok, should still work

**Comment by djKooks** [comment]
@petrjasek Sorry. I find some JSON comment about elasticsearch on `localhost:9200` but couldn't find anything on `localhost:9000` yesterday. Is this right move?

**Comment by petrjasek** [comment]
made some changes to that config - https://github.com/superdesk/superdesk/pull/2331 - it takes a while but should work

**Comment by djKooks** [comment]
@petrjasek Thanks! I just pulled your commits. There are some changes, but still `localhost:9000` shows nothing.

```
superdesk_1  | npm WARN unmet dependency /opt/superdesk/client/node_modules/nopt,
superdesk_1  | npm WARN unmet dependency which is version 1.0.10
superdesk_1  | npm WARN unmet dependency /opt/superdesk/client/node_modules/karma-coverage/node_modules/istanbul requires which@'^1.1.1' but will load
superdesk_1  | npm WARN unmet dependency /opt/superdesk/client/node_modules/which,
superdesk_1  | npm WARN unmet dependency which is version 1.0.9
superdesk_1  | npm WARN unmet dependency /opt/superdesk/client/node_modules/phantomjs-prebuilt/node_modules/fs-extra requires graceful-fs@'^4.1.2' but will load
superdesk_1  | npm WARN unmet dependency /opt/superdesk/client/node_modules/graceful-fs,
superdesk_1  | npm WARN unmet dependency which is version 1.2.3
superdesk_1  | npm WARN unmet dependency /opt/superdesk/client/node_modules/phantomjs-prebuilt/node_modules/request/node_modules/form-data requires async@'^2.0.1' but will load
superdesk_1  | npm WARN unmet dependency /opt/superdesk/client/node_modules/async,
superdesk_1  | npm WARN unmet dependency which is version 0.1.22
superdesk_1  | 04:08:16 beat.1 | Scheduler: Sending due task publish:transmit (superdesk.publish.transmit) level=INFO process=MainProcess
superdesk_1  | 04:08:16 beat.1 | Scheduler: Sending due task publish:enqueue (apps.publish.enqueue.enqueue_published) level=INFO process=MainProcess
superdesk_1  | 04:08:16 work.1 | got lock task=publish-enqueue_published host=hostid:c86cf08a368a pid:93
superdesk_1  | 04:08:16 work.1 | got lock task=Transmit-Articles host=hostid:c86cf08a368a pid:95
superdesk_1  | 04:08:16 work.1 | got lock task=Transmit-Articles host=hostid:c86cf08a368a pid:95 level=INFO process=Worker-2
superdesk_1  | 04:08:16 work.1 | got lock task=publish-enqueue_published host=hostid:c86cf08a368a pid:93 level=INFO process=Worker-1
superdesk_1  | 04:08:16 work.1 | releasing lock task=publish-enqueue_published host=hostid:c86cf08a368a pid:93
superdesk_1  | 04:08:16 work.1 | releasing lock task=publish-enqueue_published host=hostid:c86cf08a368a pid:93 level=INFO process=Worker-1
superdesk_1  | 04:08:16 work.1 | releasing lock task=Transmit-Articles host=hostid:c86cf08a368a pid:95
superdesk_1  | 04:08:16 work.1 | releasing lock task=Transmit-Articles host=hostid:c86cf08a368a pid:95 level=INFO process=Worker-2
superdesk_1  | Loading "compile.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'lodash._isnative'
superdesk_1  | Loading "extract.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'lodash._isnative'
superdesk_1  | Loading "angular-templates.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'html-minifier'
superdesk_1  | Loading "concat.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'amdefine'
superdesk_1  | Loading "connect.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'ms'
superdesk_1  | Loading "cssmin.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module '../urls/rewrite'
superdesk_1  | Loading "jshint.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'jshint/src/cli'
superdesk_1  | Loading "less.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module './lib/less-node'
superdesk_1  | Loading "uglify.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'pako/lib/zlib/messages'
superdesk_1  | Loading "watch.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module './websocket/hybi_parser'
superdesk_1  | Loading "eslint.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'estraverse-fb'
superdesk_1  | Loading "jscs.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'vow-fs'
superdesk_1  | Loading "grunt-karma.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'socket.io'
superdesk_1  | Loading "main.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'concat-map'
superdesk_1  | Loading "webpack-dev-server.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'lodash/mergeWith'
superdesk_1  | Loading "webpack.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'lodash/merge'
superdesk_1  | Loading "compile.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'lodash._isnative'
superdesk_1  | Loading "extract.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'lodash._isnative'
superdesk_1  | Loading "angular-templates.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'html-minifier'
superdesk_1  | Loading "concat.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'amdefine'
superdesk_1  | Loading "connect.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'ms'
superdesk_1  | Loading "cssmin.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module '../urls/rewrite'
superdesk_1  | Loading "jshint.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'jshint/src/cli'
superdesk_1  | Loading "less.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module './lib/less-node'
superdesk_1  | Loading "uglify.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'pako/lib/zlib/messages'
superdesk_1  | Loading "watch.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module './websocket/hybi_parser'
superdesk_1  | Loading "eslint.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'estraverse-fb'
superdesk_1  | Loading "jscs.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'vow-fs'
superdesk_1  | Loading "grunt-karma.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'socket.io'
superdesk_1  | Loading "main.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'concat-map'
superdesk_1  | Loading "webpack-dev-server.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'lodash/mergeWith'
superdesk_1  | Loading "webpack.js" tasks...ERROR
superdesk_1  | >> Error: Cannot find module 'lodash/merge'
superdesk_1  | Warning: Task "ngtemplates:dev" not found. Use --force to continue.
superdesk_1  | 
superdesk_1  | Aborted due to warnings.
...
```
Message has been changed. Could you figure out anything?

**Comment by petrjasek** [comment]
seems like this dev setup can't work really, it won't do `npm link` across volumes.
also it builds the client 2x and installs npm libs 2x making it quite slow, and I don't see how we can fix that.
are you trying to make some changes in client core? it would be probably simpler to do it without docker (and maybe keep docker for server part)

**Comment by djKooks** [comment]
@petrjasek No, I didn't change anything on repo.
Okay, I tried to run server and client seperately without docker, and it works fine. But you'll need to keep follow up with this cause other people would ask about this as I did.
Thanks for help!

**Comment by petrjasek** [comment]
yep, you can use [npm link](https://docs.npmjs.com/cli/link) in client-core clone and and in client, after that `grunt server` should use it (and it should reload on any js change, you might need to reload manually for html changes)

**Comment by djKooks** [comment]
@petrjasek Thanks! I appreciate.

**Comment by djKooks** [comment]
@petrjasek One more, how can I apply my local change of `superdesk-core` to server part?

**Comment by petrjasek** [comment]
enable virtualenv for `superdesk/server` and run there `pip install -e <path to superdesk-core>`

**Comment by djKooks** [comment]
@petrjasek but in that case, `honcho start` not works in server. Do I have to try another way?

**Comment by petrjasek** [comment]
do you get any error?

**Comment by djKooks** [comment]
@petrjasek Oh sorry. It worked after I run `pip install -r server/requirements.txt` first. Thanks!

**Comment by djKooks** [comment]
@petrjasek Hello~I got problem like below when running 'python3 manage.py app:initialize_data && python3 manage.py app:prepopulate' with new version.

```
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    app = get_app()
  File "/Users/kwangin/workspace/github_source/superdesk_project/superdesk/server/app.py", line 53, in get_app
    app = superdesk_app(config, media_storage)
  File "/Users/kwangin/workspace/github_source/superdesk_project/superdesk-core/superdesk/factory/app.py", line 112, in get_app
    install_app(module_name)
  File "/Users/kwangin/workspace/github_source/superdesk_project/superdesk-core/superdesk/factory/app.py", line 105, in install_app
    app_module = importlib.import_module(module_name)
  File "/Users/kwangin/workspace/github_source/superdesk_project/superdesk/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'apps.languages'
```
Is there something I missed, or some problem on source?

**Comment by petrjasek** [comment]
you can try to remove `'apps.languages' ` from `server/settings.py` file, but not sure why that module is missing. will check that. are you using any specific version? or latest master branch?

**Comment by djKooks** [comment]
@petrjasek Thanks! It works well after 'apps.languages' removed. I'm working on latest superdesk/master branch.
