### ISSUE TITLE
ImportError: No module named 'superdesk'

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2869]
while running honcho start command, below error apears.

`2018-05-02 11:22:09 [21922] [WARNING] Your terminal is not configured to receive UTF-8 encoded text. Please adjust your locale settings or force UTF-8 output by setting PYTHONIOENCODING="utf-8".
11:22:09 system | wamp.1 started (pid=21928)
11:22:09 system | rest.1 started (pid=21926)
11:22:09 system | beat.1 started (pid=21934)
11:22:09 system | capi.1 started (pid=21937)
11:22:09 system | work.1 started (pid=21940)
**11:22:09 wamp.1 | Traceback (most recent call last):
11:22:09 wamp.1 |   File "ws.py", line 13, in <module>
11:22:09 wamp.1 |     from settings import WS_HOST, WS_PORT, LOG_CONFIG_FILE, BROKER_URL
11:22:09 wamp.1 |   File "/home/gtcoder/Sites/superdesk/server/settings.py", line 14, in <module>
11:22:09 wamp.1 |     from superdesk.default_settings import INSTALLED_APPS
11:22:09 wamp.1 | ImportError: No module named 'superdesk'**
11:22:09 system | wamp.1 stopped (rc=1)
11:22:09 system | sending SIGTERM to rest.1 (pid 21926)
11:22:09 system | sending SIGTERM to work.1 (pid 21940)
11:22:09 system | sending SIGTERM to beat.1 (pid 21934)
11:22:09 system | sending SIGTERM to capi.1 (pid 21937)
11:22:09 system | work.1 stopped (rc=-15)
11:22:09 system | rest.1 stopped (rc=-15)
11:22:09 system | beat.1 stopped (rc=-15)
11:22:09 system | capi.1 stopped (rc=-15)
`

**Comment by jvkiran** [comment]
I've fixed the issue.

by changing 
from
wamp: python3 -u ws.py

to 
wamp: **python3.6** -u ws.py
