### ISSUE TITLE
Running python manage.py app:initialize_data - give error

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2885]
Running command  "python manage.py app:initialize_data" - gives following error

Traceback (most recent call last):
 File "manage.py", line 14, in <module>
  import superdesk
ImportError: No module name 'superdesk'

**Comment by petrjasek** [comment]
it says there is no superdesk installed, are you using virtualenv ?

**Comment by jvkiran** [comment]
No I'm not using Virtualenv.

**Comment by petrjasek** [comment]
so you can either create one or install dependencies from requirements.txt globally

**Comment by silvalooky** [comment]
Using virtualenv gives this error : 

`manage.py:15: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  from flask.ext.script import Manager
INFO:superdesk:Uhoh, an exception occured while running the command...
ERROR:superdesk:Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/__init__.py", line 60, in __call__
    res = self.run(*args, **kwargs)
  File "/opt/superdesk/env/lib/python3.5/site-packages/apps/auth/db/commands.py", line 53, in run
    user = superdesk.get_resource_service('users').find_one(username=userdata.get('username'), req=None)
  File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/services.py", line 85, in find_one
    res = self.backend.find_one(self.datasource, req=req, **lookup)
  File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/eve_backend.py", line 35, in find_one
    item = backend.find_one(endpoint_name, req=req, **lookup)
  File "/opt/superdesk/env/lib/python3.5/site-packages/eve/io/mongo/mongo.py", line 315, in find_one
    document = self.pymongo(resource).db[datasource] \
  File "/opt/superdesk/env/lib/python3.5/site-packages/eve/io/mongo/mongo.py", line 893, in pymongo
    self.driver[px] = PyMongo(self.app, px)
  File "/opt/superdesk/env/lib/python3.5/site-packages/flask_pymongo/__init__.py", line 116, in __init__
    self.init_app(app, uri, *args, **kwargs)
  File "/opt/superdesk/env/lib/python3.5/site-packages/flask_pymongo/__init__.py", line 149, in init_app
    parsed_uri = uri_parser.parse_uri(uri)
  File "/opt/superdesk/env/lib/python3.5/site-packages/pymongo/uri_parser.py", line 357, in parse_uri
    "begin with '%s' or '%s'" % (SCHEME, SRV_SCHEME))
`

**Comment by thehatami** [comment]
@petrjasek it try install globally and got `ImportError: No module name 'superdesk'` error yet

**Comment by jvkiran** [comment]
running into virtual env with following command resolved the problem
superdesk/server$ . /opt/superdesk/activate.sh

**Comment by keshavadk** [comment]
I am trying to run the file email_formatter.py 

and getting following error python email_formatter.py

```
Traceback (most recent call last):
  File "email_formatter.py", line 12, in <module>
    import superdesk
ImportError: No module named 'superdesk'

```

**Comment by trondhuso** [comment]
keshavad. Run this command first:

source /opt/superdesk/activate.sh

Then you get into the virtual environment. Then you can run the command:

python manage.py app:initialize_data

and it should work.
