### ISSUE TITLE
Following code is not there in superdesk production code

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2918]
From /opt/superdesk/server/settings.py
missing lines
#from superdesk.default_settings import INSTALLED_APPS

#INSTALLED_APPS.extend([
 #   'analytics',
 #   'apps.languages',
 #   'planning'
#])

above lines are not there in production environment, after manually added causes below error.
Jun 19 10:52:32 localhost systemd[1]: Started superdesk.
Jun 19 10:52:32 localhost sh[15679]: 10:52:32 system | logs.1 started (pid=15688)
Jun 19 10:52:32 localhost sh[15679]: 10:52:32 system | work.1 started (pid=15684)
Jun 19 10:52:32 localhost sh[15679]: 10:52:32 system | beat.1 started (pid=15694)
Jun 19 10:52:32 localhost sh[15679]: 10:52:32 system | capi.1 started (pid=15686)
Jun 19 10:52:32 localhost sh[15679]: 10:52:32 system | wamp.1 started (pid=15693)
Jun 19 10:52:32 localhost sh[15679]: 10:52:32 system | rest.1 started (pid=15697)
Jun 19 10:52:33 localhost sh[15679]: 10:52:33 rest.1 | [2018-06-19 10:52:33 +0000] [15701] [INFO] Starting gunicorn 19.8.1
Jun 19 10:52:33 localhost sh[15679]: 10:52:33 rest.1 | [2018-06-19 10:52:33 +0000] [15701] [INFO] Listening at: http://0.0.0.0:5000 (15701)
Jun 19 10:52:33 localhost sh[15679]: 10:52:33 rest.1 | [2018-06-19 10:52:33 +0000] [15701] [INFO] Using worker: sync
Jun 19 10:52:33 localhost sh[15679]: 10:52:33 rest.1 | [2018-06-19 10:52:33 +0000] [15713] [INFO] Booting worker with pid: 15713
Jun 19 10:52:33 localhost sh[15679]: 10:52:33 capi.1 | [2018-06-19 10:52:33 +0000] [15696] [INFO] Starting gunicorn 19.8.1
Jun 19 10:52:33 localhost sh[15679]: 10:52:33 capi.1 | [2018-06-19 10:52:33 +0000] [15696] [INFO] Listening at: http://0.0.0.0:5400 (15696)
Jun 19 10:52:33 localhost sh[15679]: 10:52:33 capi.1 | [2018-06-19 10:52:33 +0000] [15696] [INFO] Using worker: sync
Jun 19 10:52:33 localhost sh[15679]: 10:52:33 capi.1 | [2018-06-19 10:52:33 +0000] [15717] [INFO] Booting worker with pid: 15717
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 capi.1 | GET /contentapi status=200 time=0s size=201b
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 | [2018-06-19 10:52:34 +0000] [15713] [ERROR] Exception in worker process
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 | Traceback (most recent call last):
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     worker.init_process()
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     self.load_wsgi()
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     self.wsgi = self.app.wsgi()
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     self.callable = self.load()
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     return self.load_wsgiapp()
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     return util.import_app(self.app_uri)
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     __import__(module)
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/server/wsgi.py", line 14, in <module>
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     application = get_app()
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/server/app.py", line 41, in get_app
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     app = superdesk_app(config)
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/factory/app.py", line 164, in get_app
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     install_app(module_name)
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/factory/app.py", line 156, in install_app
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     app_module = importlib.import_module(module_name)
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 |     return _bootstrap._gcd_import(name[level:], package, level)
Jun 19 10:52:34 localhost sh[15679]: 10:52:34 rest.1 | ImportError: No module named 'analytics'

**Comment by petrjasek** [comment]
for analytics you have to install `superdesk-analytics` via 
https://github.com/superdesk/superdesk/blob/master/server/requirements.txt#L6
