### ISSUE TITLE
Cant install Superdesk even on fresh Ubuntu 16.04

### ISSUE THREAD

**Issue by silvalooky** [superdesk/superdesk#2929]
I got these errors when I try to install Superdesk with the link https://raw.githubusercontent.com/superdesk/fireq/files/superdesk/install

```
manage.py:15: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  from flask.ext.script import Manager
INFO:apps.prepopulate.app_initialize:Starting data initialization
INFO:apps.prepopulate.app_initialize:Config: /opt/superdesk/server
INFO:superdesk:Uhoh, an exception occured while running the command...
ERROR:superdesk:Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/__init__.py", line 60, in __call__
    res = self.run(*args, **kwargs)
  File "/opt/superdesk/env/lib/python3.5/site-packages/apps/prepopulate/app_initialize.py", line 230, in run
    app.init_indexes()
  File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/factory/app.py", line 59, in init_indexes
    create_index(self, resource, name, list_of_keys, index_options)
  File "/opt/superdesk/env/lib/python3.5/site-packages/eve/io/mongo/mongo.py", line 969, in create_index
    db = app.data.pymongo(resource, px).db
  File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/datalayer.py", line 41, in pymongo
    return self.mongo.pymongo(resource, prefix)
  File "/opt/superdesk/env/lib/python3.5/site-packages/eve/io/mongo/mongo.py", line 893, in pymongo
    self.driver[px] = PyMongo(self.app, px)
  File "/opt/superdesk/env/lib/python3.5/site-packages/flask_pymongo/__init__.py", line 116, in __init__
    self.init_app(app, uri, *args, **kwargs)
  File "/opt/superdesk/env/lib/python3.5/site-packages/flask_pymongo/__init__.py", line 149, in init_app
    parsed_uri = uri_parser.parse_uri(uri)
  File "/opt/superdesk/env/lib/python3.5/site-packages/pymongo/uri_parser.py", line 357, in parse_uri
    "begin with '%s' or '%s'" % (SCHEME, SRV_SCHEME))
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
```

**Comment by bernardborg** [comment]
Same issues here - If I may add to this I tried install on a Hyper V Instance on Windows Server 2012, got the same issues (using ISO from Ubuntu's Repo - Tried  on a VPS Running Ubuntu Server 16.04 same issues - tried all possible configurations install without updates, upgrades, dist upgrades. Then tried on my physical machine running virtual box using images from osboxes and the script worked without a glitch. Both Server and Desktop Images - any idea how to understand the differences in the OS so to replicate success?

**Comment by silvalooky** [comment]
Hi bernardborg, I was working few days ago on vmware workstation, and eveythings worked fine, and then I moved to ESXi, and this issue comes up, maybe the problem is related with virtualisation ?

**Comment by bernardborg** [comment]
Hi Silvalooky, it looks like a virtualization issue - but can’t fathomize
that virtualization stops a python framework from installing it must be a
script issue. I’m not a Linux guru but I wish there is a method to see
what’s missing in the VPS compared to the local virtualbox vhd

**Comment by rSedoy** [comment]
@silvalooky this issue is due to the new version Flask-PyMongo. Dirty fix, replace 
`time pip install -U -r $req`
by
`time pip install Flask-PyMongo==0.5.2`
`time pip install -r $req`

**Comment by silvalooky** [comment]
@rSedoy Flask-PyMongo==0.5.2 fixes the issue for me , thanks for your reply

**Comment by vanja-bertalan** [comment]
@silvalooky have you been able to make it work? Unable to get through flask.ext.script deprecated.
