### ISSUE TITLE
Docker build errors out

### ISSUE THREAD

**Issue by DarkBlaez** [superdesk/superdesk#3067]
Thoughts around this? When was the last time the docker image was built?

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/python-twitter/setup.py", line 75, in <module>

    'Programming Language :: Python :: 3.6',

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 858, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 870, in obtain

    return installer(requirement)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 646, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup

    run_setup(setup_script, args)

  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 50, in run_setup

    lambda: execfile(

  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 100, in run

    return func()

  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 52, in <lambda>

    {'__file__':setup_script, '__name__':'__main__'}

  File "/usr/lib/python3/dist-packages/setuptools/compat.py", line 78, in execfile

    exec(compile(source, fn, 'exec'), globs, locs)

  File "setup.py", line 76, in <module>

    ],

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 243, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__

    self.finalize_options()

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 277, in finalize_options

    ep.load()(self, ep.name, value)

  File "/tmp/easy_install-qet749q2/pytest-runner-4.4/setuptools_scm-3.2.0-py3.4.egg/setuptools_scm/integration.py", line 10, in version_keyword

  File "/tmp/easy_install-qet749q2/pytest-runner-4.4/setuptools_scm-3.2.0-py3.4.egg/setuptools_scm/version.py", line 66, in _warn_if_setuptools_outdated

setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/python-twitter
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip3 install -U -r requirements.txt' returned a non-zero code: 1

Thanks
DB

**Comment by nsrtky** [comment]
++

**Comment by dkoryto** [comment]
Add  **RUN pip3 install --upgrade pip setuptools wheel** 
example:
# install server
COPY ./server /opt/superdesk
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install -U -r requirements.txt

**Comment by sagun786** [comment]
After I run the command
./scripts/docker-local-demo.sh

Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/python-twi
tter
Storing debug log for failure in /root/.pip/pip.log
ERROR: Service 'superdesk' failed to build: The command '/bin/sh -c pip3 install -U -r requ
irements.txt' returned a non-zero code: 1
