### ISSUE TITLE
Superdesk not starting - honcho related

### ISSUE THREAD

**Issue by trondhuso** [superdesk/superdesk#3199]
output of systemctl status superdesk

superdesk.service - superdesk
   Loaded: loaded (/etc/systemd/system/superdesk.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-10-16 08:22:17 CEST; 3s ago
  Process: 8911 ExecStart=/bin/sh -c . /opt/superdesk/activate.sh && exec honcho  start --no-colour (code=exited, status=1/FAILURE)
 Main PID: 8911 (code=exited, status=1/FAILURE)

Oct 16 08:22:17 superdesk-4thestate systemd[1]: superdesk.service: Main process exited, code=exited, status=1/FAILURE
Oct 16 08:22:17 superdesk-4thestate systemd[1]: superdesk.service: Unit entered failed state.
Oct 16 08:22:17 superdesk-4thestate systemd[1]: superdesk.service: Failed with result 'exit-code'.

Running manually I see this:
2020-10-16 08:28:04 [7532] [ERROR] Procfile does not exist or is not a file

in /var/log/superdesk/main.log
Oct 16 08:39:11 superdesk-4thestate systemd[1]: superdesk.service: Service hold-off time over, scheduling restart.
Oct 16 08:39:11 superdesk-4thestate systemd[1]: Stopped superdesk.
Oct 16 08:39:11 superdesk-4thestate systemd[1]: Started superdesk.
Oct 16 08:39:11 superdesk-4thestate sh[12302]: Traceback (most recent call last):
Oct 16 08:39:11 superdesk-4thestate sh[12302]:   File "/opt/superdesk/env/bin/honcho", line 5, in <module>
Oct 16 08:39:11 superdesk-4thestate sh[12302]:     from honcho.command import main
Oct 16 08:39:11 superdesk-4thestate sh[12302]: ModuleNotFoundError: No module named 'honcho'
Oct 16 08:39:11 superdesk-4thestate systemd[1]: superdesk.service: Main process exited, code=exited, status=1/FAILURE
Oct 16 08:39:11 superdesk-4thestate systemd[1]: superdesk.service: Unit entered failed state.
Oct 16 08:39:11 superdesk-4thestate systemd[1]: superdesk.service: Failed with result 'exit-code'.

When running 
`source /opt/superdesk/activate.sh`

and then 
`exec honcho start`

I get:
```
Traceback (most recent call last):
  File "/opt/superdesk/env/bin/honcho", line 5, in <module>
    from honcho.command import main
ModuleNotFoundError: No module named 'honcho'
```

If I cd to /opt/superdesk/server and run exec honcho start the superdesk starts.

**Comment by trondhuso** [comment]
Closing this issue as it could have been that I had not installed honcho 

Which is done like this
pip3 install honcho
