### ISSUE TITLE
Manual install experiences.

### ISSUE THREAD

**Issue by trondhuso** [superdesk/superdesk#3201]
When running the command to prepopulate data I get the error below. 
If I run this command: 

`python manage.py app:prepopulate`

I get this error:

```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    import superdesk
ImportError: No module named superdesk
```
(Same happens if I run the command in environment mode)
(Copied the layout from the script)

Using python3:
`python3 manage.py app:prepopulate`

```
WARNING:superdesk.auth_server.oauth2:No shared secret set, please set it using AUTH_SERVER_SHARED_SECRET environment variable or setting. Authorisation server can't be used
WARNING:superdesk.text_checkers.spellcheckers.leuven_dutch:API key is not set for University of Leuven Dutch spellchecker, please set LEUVEN_DUTCH_API_KEY variable to use it
WARNING:superdesk.text_checkers.spellcheckers.base:"leuven_dutch" spellchecker is not available
WARNING:superdesk.text_checkers.spellcheckers.grammalecte:can't request Grammalecte URL (http://localhost:8080/gc_text/fr): HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /gc_text/fr (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff3bfdf6be0>: Failed to establish a new connection: [Errno 111] Connection refused',))
WARNING:superdesk.text_checkers.spellcheckers.base:"grammalecte" spellchecker is not available
WARNING:superdesk.macros:Can't import macro superdesk.macros.assign_status: No module named 'planning'
INFO:superdesk.users.services:Updating Stage Visibility for user 5f8a1680d6f1b7ffab5f4b24.
INFO:superdesk.users.services:Updated Stage Visibility for user 5f8a1680d6f1b7ffab5f4b24.
ERROR:eve:batch op errors occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/eve/io/mongo/mongo.py", line 462, in insert
    return coll.insert_many(doc_or_docs, ordered=True).inserted_ids
  File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 760, in insert_many
    blk.execute(write_concern, session=session)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/bulk.py", line 522, in execute
    return self.execute_command(generator, write_concern, session)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/bulk.py", line 350, in execute_command
    _raise_bulk_write_error(full_result)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/bulk.py", line 140, in _raise_bulk_write_error
    raise BulkWriteError(full_result)
pymongo.errors.BulkWriteError: batch op errors occurred
INFO:superdesk:Command finished with: None
```

**Comment by trondhuso** [comment]
Also like to add that running npm install causes errors as well. 

```
deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! Linux 4.15.0-1098-azure
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0-1098-azure
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

**Comment by trondhuso** [comment]
This might be because I am using the master branch. I will test this again using 1.0 branch instead.

**Comment by trondhuso** [comment]
In order to make the first error message go away is this:
run 
`source /opt/superdesk/env/bin/activate`
You are then in environment mode which I don't quite know what is, but I guess it has something to do with reading all the variables for the solution.

the npm-bug is because the solution uses an old version of node. Try installing to node 10 and npm to version 6. Do not try and upgrade to 12 as it will cause other problems.

Grammalecte and leuven_dutch was not installed on my system, which explains those error messages.

Closing this issue.
