### ISSUE TITLE
Error when running docker-compose run superdesk-server run python manage.py app:initialize_data

### ISSUE THREAD

**Issue by sr33rajv** [superdesk/superdesk#3281]
**Same issue on Ubuntu 20.x and 18.x** 
docker-compose run superdesk-server run python manage.py app:initialize_data
Starting root_mongodb_1 ... done
Starting root_elastic_1 ... done
Starting root_redis_1   ... done
waiting for elastic.done.
INFO:superdesk.backend_meta.backend_meta:version of 'superdesk-core': 2.5.dev0
INFO:superdesk.backend_meta.backend_meta:version of 'superdesk-planning': 2.6.0.dev0
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 523, in open_for_read
    return open_for_read_by_name(name,mode)
  File "/opt/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 463, in open_for_read_by_name
    return open(name,mode)
FileNotFoundError: [Errno 2] No such file or directory: 'DejaVuSans.ttf'

During handling of the above exception, another exception occurred:

**Comment by petrjasek** [comment]
is this on broadcasting branch?

**Comment by sr33rajv** [comment]
No we used Master branch.

**Comment by petrjasek** [comment]
strange, there is no reportlab required there https://github.com/superdesk/superdesk/blob/master/server/requirements.txt

**Comment by petrjasek** [comment]
but if you add `fonts-dejavu` to https://github.com/superdesk/superdesk/blob/master/server/Dockerfile#L5-L13 it should work

**Comment by sr33rajv** [comment]
I tried to install superdesk on Multiple servers but same issue when intializing the data.

**Comment by sr33rajv** [comment]
> What other changes have you and/or your team made? I was unable to reproduce this error after adding reportlab to the server requirements. The superdesk core and planning module versions do not match output from the master branch either.
> 
> ![Screenshot from 2022-11-24 11-23-28](https://user-images.githubusercontent.com/63004404/203830274-3894839b-c87d-49d7-979f-1e621758460d.png)

We didn't change anything Just tried to install superdesk using this compose file https://github.com/superdesk/superdesk/blob/master/docker-compose.yml

**Comment by bmg1919** [comment]
I would start from scratch once more and watch the output.

Once you've cloned the repo into a new folder (from superdesk/superdesk, not otheraccount/superdesk), run `git checkout`. The output should be *master. If not, `run git checkout master.`

Then run `sudo docker-compose up -d`

That should make superdesk available at localhost:8080. Try logging in with admin/admin or running initialize_data.

**Comment by sr33rajv** [comment]
> I would start from scratch once more and watch the output.
> 
> Once you've cloned the repo into a new folder (`git clone https://github.com/superdesk/superdesk.git`), run `git checkout`. The output should be *master. If not, `run git checkout master`.
> 
> Then run `sudo docker-compose up -d`
> 
> That should make superdesk available at localhost:8080. Try logging in with admin/admin or running `sudo docker-compose run superdesk-server python manage.py app:initialize_data`.

Tried this but same issue

**Comment by bmg1919** [comment]
That should not be possible working off the master branch. Unless it is a regional thing, not allowing you to obtain needed software during the install, but that does not explain why your containers are named differently or why it's obtaining different versions of superdesk-core or planning. 

If you do have a newly acquired copy of superdesk, within the folder, try running `docker-compose build --no-cache`. That should force it to rebuild the server and client regardless of how many times you've attempted to install.

**Comment by sr33rajv** [comment]
> but if you add `fonts-dejavu` to https://github.com/superdesk/superdesk/blob/master/server/Dockerfile#L5-L13 it should work

The issue seems here when I add the fonts-dejavu in Dockerfile and run the initialize command it works fine.

**Comment by bmg1919** [comment]
![Screenshot from 2022-11-24 13-07-43](https://user-images.githubusercontent.com/63004404/203845777-51934a12-bd16-4eab-a667-9a384799dbf2.png)

Very true. That does not explain why you're not actually installing from the master branch. That's where I got stuck.

**Comment by petrjasek** [comment]
seems like an issue with our github action which publishes images on every release, lately we were make some test releases from broadcasting branch where this reportlab is used, but that shouldn't be pushed to dockerhub.

**Comment by sr33rajv** [comment]
Ok so the dockerhub image issue should be resolved right?

**Comment by petrjasek** [comment]
yep it's updated now

**Comment by sr33rajv** [comment]
The new docker image is showing this error /opt/superdesk/docker/start.sh: line 26: exec: run: not found
![Screenshot 2022-11-25 at 9 16 44 PM](https://user-images.githubusercontent.com/54975410/204019177-64fd8072-aeb4-4791-9998-34a90528d1f4.png)

**Comment by sr33rajv** [comment]
> that's when doing `docker-compose up` ?

No the error is showing when i run docker-compose run superdesk-server run python manage.py app:initialize_data

**Comment by petrjasek** [comment]
imo there should be `honcho run` before `python manage.py`

**Comment by unstence** [comment]
> Remove "run" from between superdesk-server and python. You're telling it to run "run" before python, which it can't find, causing it to error out before it has a chance to do anything else. There's most of the problem right there. Sorry it took so long to notice.

This got me past that issue
